name: soglio_gpu
channels:
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - tensorflow-gpu=2.16
  - cuda=12.6  # Standard package, not -dev
  - numpy=1.26
  - matplotlib=3.8
  - seaborn
  - pandas
  - jupyterlab=4.0
  - seaborn
  - scikit-learn
  - pip:
      - git+https://github.com/Gilles86/braincoder.git@transformation_refactor