name: soglio_metal
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26
  - matplotlib=3.8
  - seaborn
  - pandas
  - jupyterlab=4.0
  - pip
  - seaborn
  - scikit-learn
  - pip:
    - tensorflow-macos==2.16.1  # Closest available to 2.16.0
    - tensorflow-metal==1.1.0
    - tensorboard==2.16.0
    - tf2onnx==1.16.0
    - onnx==1.15.0
    - pydot==2.0.0
    - graphviz==0.20.1